<?php

namespace AppBundle\Repository;

/**
 * AbsenceReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceReasonRepository extends \Doctrine\ORM\EntityRepository
{
}
