<?php

namespace AppBundle\Repository;

/**
 * DoNotSendEmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoNotSendEmployeeRepository extends \Doctrine\ORM\EntityRepository
{
}
