<?php

namespace AppBundle\Repository;

/**
 * UnavailabilityReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeUnavailabilityRepository extends \Doctrine\ORM\EntityRepository
{
}
