<?php

namespace AppBundle\Repository;

/**
 * EmployeeAbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeAbsenceRepository extends \Doctrine\ORM\EntityRepository
{
}
