<?php

namespace AppBundle\Repository;

/**
 * RosterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RosterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForId($suid)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Roster r where serviceUserId=suid order by rosterstarttime asc'
            )
            ->getResult();
    }
}
