<?php

namespace AppBundle\Repository;

/**
 * RosterAssignedEmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RosterAssignedEmployeeRepository extends \Doctrine\ORM\EntityRepository
{
}
