<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ServiceUser;

/**
 * RosterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RosterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForId($suid)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Roster r where serviceUserId=suid order by rosterstarttime asc'
            )
            ->getResult();
    }


// this doctrine filter is used by the for loop in the show method of the service user controller.
//for each checked date in the for loop it checks to see if that service has any roster starting in that 24 hour period.
    public function getByDate(\DateTime $date, ServiceUser $serviceUser)
    {
        $from = new \DateTime($date->format("Y-m-d") . " 00:00:00");
        $to = new \DateTime($date->format("Y-m-d") . " 23:59:59");
        //var_dump($from,$to);

        $qb = $this->createQueryBuilder("roster");
        $qb->andWhere($qb->expr()->between('roster.rosterStartTime', ':date_from', ':date_to'))
            ->andWhere("roster.serviceUserId= " . $serviceUser->getId());
        $qb->setParameter('date_from', $from, \Doctrine\DBAL\Types\Type::DATETIME);
        $qb->setParameter('date_to', $to, \Doctrine\DBAL\Types\Type::DATETIME);

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
