<?php

namespace AppBundle\Repository;

/**
 * RosterStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RosterStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
