<?php

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * ServiceUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceUserRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM AppBundle:ServiceUser s ORDER BY s.managingOffice ASC'
            )
            ->getResult();
    }

}
