<?php

namespace AppBundle\Repository;

/**
 * ServiceUserDoNotSendEmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceUserDoNotSendEmployeeRepository extends \Doctrine\ORM\EntityRepository
{
}
