<?php

namespace AppBundle\Repository;

/**
 * ServiceUserAssignedEmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceUserAssignedEmployeeRepository extends \Doctrine\ORM\EntityRepository
{
}
